name: Add to Polli HQ Project
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/polli-labs/projects/1
          github-token: ${{ secrets.PROJECTS_TOKEN }}

